### PR TITLE
Add enumeration by ref values

### PR DESCRIPTION
**Pull request by lakecherry**
Had the situation of applying some operation to all dictionary values (struct), so i added this enumerator to efficiently ref return all values (currently you have to call "Update" and lookup each entry to get a reference).

### CODE REVIEW

**Comment by lakecherry** [comment]
Sorry for the mess ... it's my first pull request ...

**Comment by Wsm2110** [comment]
X being faster than y should be backed up by benchmarks mate.

**Comment by lakecherry** [comment]
Is "Update" the corresponding function to compare with?

**Comment by lakecherry** [comment]
Added this to DenseMap ... just in case someone else needs fast write access to all map values

```
	#region Enumerator

	/// <summary>
	/// ref returns all map values
	/// </summary>
	public ref struct Enumerator
	{
		internal Enumerator (ControlBytes _controlBytes, Entry[] _entries)
		{
			System.Diagnostics.Debug.Assert (_controlBytes.Length == _entries.Length);

			this.pEntriesOrigin = ref MemoryMarshal.GetArrayDataReference (_entries);
			this.pEntries = ref Unsafe.Add (ref this.pEntriesOrigin, _controlBytes.Length);

			this.pControlBytes = ref _controlBytes [_controlBytes.Length - 1];
		}

		#region Interface

		public bool MoveNext()
		{
			// loop backwards
			while (this.pControlBytes < 0)
			{
				this.pControlBytes = ref Unsafe.Subtract (ref this.pControlBytes, 1);
				this.pEntries = ref Unsafe.Subtract (ref this.pEntries, 1);
			}

			this.pEntries = ref Unsafe.Subtract (ref this.pEntries, 1);

			return Unsafe.IsAddressLessThan (ref pEntries, ref pEntriesOrigin) == false;
		}

		public ref TValue Current => ref this.pEntries.Value;

		#endregion

		#region Data

		readonly ref Entry pEntriesOrigin;

		ref Entry pEntries;
		ref sbyte pControlBytes;

		#endregion
	}

    #endregion
```

**Pull request closed without merging**
